#!/usr/bin/env python3
"""Render user-space Asterisk configs from the instance file. No secrets logged.

Asterisk runs as the instance Unix user (`serge-asterisk.service`,
`asterisk -f -C <config>/asterisk.conf`). Only pjsip.conf carries a
secret (trunk password, 0600). Everything else is 0644.
"""

from __future__ import annotations

from collections.abc import Mapping

from serge.voice.audiosocket import LISTEN_HOST, LISTEN_PORT, SESSION_UUID

PJSIP_PORT = 5061
RTP_START = 10000
RTP_END = 10100


class AsteriskError(ValueError):
    pass


def voice_layout(loaded: Mapping, facts: Mapping[str, str]) -> dict[str, str]:
    """User-space dirs. No SIP secret. astdatadir stays the package tree."""
    features = loaded.get('features') or {}
    if not features.get('phone_voice'):
        raise AsteriskError('features.phone_voice is off')
    paths = loaded.get('paths') or {}
    identity = loaded.get('identity') or {}
    home = str(paths.get('home') or '').strip()
    system_root = str(paths.get('system_root') or '').strip()
    config_root = str(paths.get('config_root') or '').strip()
    did = str(identity.get('phone_voice_number') or '').strip()
    if not (home and system_root and config_root and did):
        raise AsteriskError('instance paths/identity incomplete for asterisk')
    uid = str(facts.get('uid') or '1000')
    conf_dir = f'{config_root}/asterisk'
    run_dir = f'/run/user/{uid}/serge-asterisk'
    return {
        'did': did,
        'conf_dir': conf_dir,
        'run_dir': run_dir,
        'log_dir': f'{system_root}/logs/asterisk',
        'records': f'{system_root}/state/voice/records',
        'agi_dir': f'{system_root}/serge/voice',
        'spool_dir': f'{conf_dir}/var/spool',
        'cache_dir': f'{run_dir}/cache',
        'datadir': '/var/lib/asterisk',
    }


def render_asterisk_conf(loaded: Mapping, facts: Mapping[str, str]) -> str:
    """asterisk.conf only — safe to rewrite on update (no trunk password)."""
    layout = voice_layout(loaded, facts)
    return f"""\
; Generated by serge-builder. User-space Asterisk, no root.
[directories]
astetcdir => {layout['conf_dir']}
astmoddir => /usr/lib/asterisk/modules
astvarlibdir => {layout['conf_dir']}/var/lib
astdbdir => {layout['conf_dir']}/var/lib
astkeydir => {layout['conf_dir']}/var/lib/keys
astdatadir => {layout['datadir']}
astagidir => {layout['agi_dir']}
astspooldir => {layout['spool_dir']}
astrundir => {layout['run_dir']}
astlogdir => {layout['log_dir']}
astcachedir => {layout['cache_dir']}
astsbindir => /usr/sbin

[options]
documentation_language = en_US
"""


def render_asterisk(
    loaded: Mapping,
    facts: Mapping[str, str],
    secrets: Mapping[str, str],
) -> dict[str, tuple[str, int]]:
    """Return {relpath: (content, mode)} under <config_root>/asterisk/."""
    layout = voice_layout(loaded, facts)
    phone = loaded.get('phone_voice') or {}
    server = str(phone.get('sip_server') or '').strip()
    username = str(phone.get('sip_username') or '').strip()
    transport = str(phone.get('sip_transport') or 'tls').strip().lower()
    password = str(secrets.get('sip_trunk_password') or '')
    if not (server and username and password):
        raise AsteriskError('SIP trunk server/username/password required')
    if transport not in {'udp', 'tcp', 'tls'}:
        raise AsteriskError('phone_voice.sip_transport must be udp|tcp|tls')
    records = layout['records']
    did = layout['did']
    asterisk_conf = render_asterisk_conf(loaded, facts)
    remote_port = PJSIP_PORT if transport == 'tls' else 5060
    bind = f'0.0.0.0:{remote_port}'
    tls_lines = (
        'verify_server = no\nallow_wildcard_certs = yes\nmethod = tlsv1_2\n'
        if transport == 'tls'
        else ''
    )
    srtp_line = 'media_encryption = sdes\n' if transport == 'tls' else ''
    remote = f'{server}:{remote_port}'

    pjsip_conf = f"""\
; Generated by serge-builder. Contains the trunk password: 0600.
[transport-serge]
type = transport
protocol = {transport}
{tls_lines}bind = {bind}

[trunk]
type = registration
transport = transport-serge
outbound_auth = trunk-auth
server_uri = sip:{remote}
client_uri = sip:{username}@{remote}
retry_interval = 60
forbidden_retry_interval = 120
expiration = 3600
contact_user = {username}

[trunk-auth]
type = auth
auth_type = userpass
username = {username}
password = {password}

[trunk-aor]
type = aor
contact = sip:{remote}
qualify_frequency = 0

[trunk]
type = endpoint
transport = transport-serge
context = serge-in
disallow = all
allow = g722,alaw,ulaw
outbound_auth = trunk-auth
aors = trunk-aor
from_user = {username}
from_domain = {server}
callerid = {did}
send_pai = yes
direct_media = no
dtmf_mode = rfc4733
{srtp_line}
[trunk]
type = identify
endpoint = trunk
match = {server}

; Local softphone for tests (Linphone on the VPS). Same transport, auth required.
[serge-agent]
type = endpoint
transport = transport-serge
context = serge-agent-out
disallow = all
allow = g722,alaw,ulaw
auth = serge-agent-auth
aors = serge-agent-aor
direct_media = no

[serge-agent-auth]
type = auth
auth_type = userpass
username = serge-agent
password = {password}

[serge-agent-aor]
type = aor
max_contacts = 1
"""

    pai = f'<sip:{did}@{server}>'
    extensions_conf = f"""\
; Generated by serge-builder. CLI is locked to the instance voice DID.
[serge-in]
exten => {did},1,NoOp(Inbound ${{CALLERID(num)}} to Serge {did})
 same => n,MixMonitor({records}/${{STRFTIME(${{EPOCH}},,%Y%m%d-%H%M%S)}}-${{UNIQUEID}}-${{CALLERID(num)}}.wav)
 same => n,Answer()
 same => n,AudioSocket({SESSION_UUID},{LISTEN_HOST}:{LISTEN_PORT})
 same => n,AGI(turn.py,inbound,${{CALLERID(num)}},{did})
 same => n,Hangup()
exten => _X.,1,NoOp(Inbound to unknown DID ${{EXTEN}}, refuse)
 same => n,Hangup()

; Dial first (CLI + PAI on the INVITE). S2S on the PJSIP channel (U),
; not on Local/;1 — sinon le MixMonitor entend et le 06 n’entend rien.
[serge-dial]
exten => _+X.,1,NoOp(Serge dial ${{EXTEN}} CLI {did})
 same => n,Set(CALLERID(num)={did})
 same => n,Dial(PJSIP/${{EXTEN}}@trunk,60,tTb(serge-pai^add^1)U(serge-s2s^${{EXTEN}}))
 same => n,Hangup()

[serge-pai]
exten => add,1,Set(PJSIP_HEADER(add,P-Asserted-Identity)={pai})
 same => n,Return()

[serge-s2s]
exten => s,1,MixMonitor({records}/${{STRFTIME(${{EPOCH}},,%Y%m%d-%H%M%S)}}-${{UNIQUEID}}-${{ARG1}}.wav)
 same => n,AudioSocket({SESSION_UUID},{LISTEN_HOST}:{LISTEN_PORT})
 same => n,AGI(turn.py,outbound,${{ARG1}})
 same => n,Return()

; Originate target: Local/<to>@serge-dial extension <to>@serge-campaign
; Keep Local/;1 up while U() holds the PJSIP leg.
[serge-campaign]
exten => _+X.,1,NoOp(Serge outbound to ${{EXTEN}})
 same => n,Set(CALLERID(num)={did})
 same => n,Wait(180)
 same => n,Hangup()

; Manual calls from the local softphone. Same CLI lock, same recording.
[serge-agent-out]
exten => _+X.,1,NoOp(Softphone outbound to ${{EXTEN}})
 same => n,Set(CALLERID(num)={did})
 same => n,MixMonitor({records}/${{STRFTIME(${{EPOCH}},,%Y%m%d-%H%M%S)}}-${{UNIQUEID}}-${{EXTEN}}.wav)
 same => n,Dial(PJSIP/${{EXTEN}}@trunk,60,tTb(serge-pai^add^1))
 same => n,Hangup()
"""

    rtp_conf = f"""\
; Generated by serge-builder.
[general]
rtpstart = {RTP_START}
rtpend = {RTP_END}
"""

    modules_conf = """\
; Generated by serge-builder.
[modules]
autoload = yes
noload = chan_sip.so
"""
    return {
        'asterisk.conf': (asterisk_conf, 0o644),
        'pjsip.conf': (pjsip_conf, 0o600),
        'extensions.conf': (extensions_conf, 0o644),
        'rtp.conf': (rtp_conf, 0o644),
        'modules.conf': (modules_conf, 0o644),
    }


def config_filenames() -> tuple[str, ...]:
    return (
        'asterisk.conf',
        'pjsip.conf',
        'extensions.conf',
        'rtp.conf',
        'modules.conf',
    )
