#!/usr/bin/env python3
"""Render user-space Asterisk configs from the instance file. No secrets logged.

Asterisk runs as the instance Unix user (`serge-asterisk.service`,
`asterisk -f -C <config>/asterisk.conf`). Only pjsip.conf carries a
secret (trunk password, 0600). Everything else is 0644.
"""

from __future__ import annotations

from collections.abc import Mapping

PJSIP_PORT = 5061
RTP_START = 10000
RTP_END = 10100


class AsteriskError(ValueError):
    pass


def render_asterisk(
    loaded: Mapping,
    facts: Mapping[str, str],
    secrets: Mapping[str, str],
) -> dict[str, tuple[str, int]]:
    """Return {relpath: (content, mode)} under <config_root>/asterisk/."""
    features = loaded.get('features') or {}
    if not features.get('phone_voice'):
        raise AsteriskError('features.phone_voice is off')
    paths = loaded.get('paths') or {}
    identity = loaded.get('identity') or {}
    phone = loaded.get('phone_voice') or {}
    home = str(paths.get('home') or '').strip()
    system_root = str(paths.get('system_root') or '').strip()
    config_root = str(paths.get('config_root') or '').strip()
    did = str(identity.get('phone_voice_number') or '').strip()
    server = str(phone.get('sip_server') or '').strip()
    username = str(phone.get('sip_username') or '').strip()
    transport = str(phone.get('sip_transport') or 'tls').strip().lower()
    password = str(secrets.get('sip_trunk_password') or '')
    if not (home and system_root and config_root and did):
        raise AsteriskError('instance paths/identity incomplete for asterisk')
    if not (server and username and password):
        raise AsteriskError('SIP trunk server/username/password required')
    if transport not in {'udp', 'tcp', 'tls'}:
        raise AsteriskError('phone_voice.sip_transport must be udp|tcp|tls')
    uid = str(facts.get('uid') or '1000')
    conf_dir = f'{config_root}/asterisk'
    run_dir = f'/run/user/{uid}/serge-asterisk'
    log_dir = f'{system_root}/logs/asterisk'
    records = f'{system_root}/state/voice/records'
    agi_dir = f'{system_root}/serge/voice'

    asterisk_conf = f"""\
; Generated by serge-builder. User-space Asterisk, no root.
[directories](!)
astetcdir => {conf_dir}
astmoddir => /usr/lib/asterisk/modules
astvarlibdir => {conf_dir}/var/lib
astdbdir => {conf_dir}/var/lib
astkeydir => {conf_dir}/var/lib/keys
astdatadir => {conf_dir}/var/lib
astagidir => {agi_dir}
astrundir => {run_dir}
astlogdir => {log_dir}
astsbindir => /usr/sbin

[options]
documentation_language = en_US
"""

    pjsip_conf = f"""\
; Generated by serge-builder. Contains the trunk password: 0600.
[transport-serge]
type = transport
protocol = {transport}
bind = 127.0.0.1:{PJSIP_PORT}

[trunk]
type = registration
transport = transport-serge
outbound_auth = trunk-auth
server_uri = sip:{server}
client_uri = sip:{username}@{server}
retry_interval = 60
forbidden_retry_interval = 120
expiration = 3600

[trunk-auth]
type = auth
auth_type = userpass
username = {username}
password = {password}

[trunk-aor]
type = aor
contact = sip:{server}
qualify_frequency = 60

[trunk]
type = endpoint
transport = transport-serge
context = serge-in
disallow = all
allow = g722,alaw,ulaw
outbound_auth = trunk-auth
aors = trunk-aor
from_user = {username}
direct_media = no
dtmf_mode = rfc4733

; Local softphone for tests (Linphone on the VPS, no trunk involved).
[serge-agent]
type = endpoint
transport = transport-serge
context = serge-agent-out
disallow = all
allow = g722,alaw,ulaw
auth = serge-agent-auth
aors = serge-agent-aor
direct_media = no

[serge-agent-auth]
type = auth
auth_type = userpass
username = serge-agent
password = {password}

[serge-agent-aor]
type = aor
max_contacts = 1
"""

    extensions_conf = f"""\
; Generated by serge-builder. CLI is locked to the instance NPV.
[serge-in]
exten => {did},1,NoOp(Inbound ${{CALLERID(num)}} to Serge {did})
 same => n,MixMonitor({records}/${{STRFTIME(${{EPOCH}},,%Y%m%d-%H%M%S)}}-${{UNIQUEID}}-${{CALLERID(num)}}.wav)
 same => n,AGI(turn.py,inbound,${{CALLERID(num)}},{did})
 same => n,Hangup()
exten => _X.,1,NoOp(Inbound to unknown DID ${{EXTEN}}, refuse)
 same => n,Hangup()

; Originate target: channel originate PJSIP/<to>@trunk extension <to>@serge-campaign
[serge-campaign]
exten => _+X.,1,NoOp(Serge outbound to ${{EXTEN}})
 same => n,Set(CALLERID(num)={did})
 same => n,MixMonitor({records}/${{STRFTIME(${{EPOCH}},,%Y%m%d-%H%M%S)}}-${{UNIQUEID}}-${{EXTEN}}.wav)
 same => n,AGI(turn.py,outbound,${{EXTEN}})
 same => n,Hangup()

; Manual calls from the local softphone. Same CLI lock, same recording.
[serge-agent-out]
exten => _+X.,1,NoOp(Softphone outbound to ${{EXTEN}})
 same => n,Set(CALLERID(num)={did})
 same => n,MixMonitor({records}/${{STRFTIME(${{EPOCH}},,%Y%m%d-%H%M%S)}}-${{UNIQUEID}}-${{EXTEN}}.wav)
 same => n,Dial(PJSIP/${{EXTEN}}@trunk,60,tT)
 same => n,Hangup()
"""

    rtp_conf = f"""\
; Generated by serge-builder.
[general]
rtpstart = {RTP_START}
rtpend = {RTP_END}
"""

    modules_conf = """\
; Generated by serge-builder.
[modules]
autoload = yes
noload = chan_sip.so
"""
    return {
        'asterisk.conf': (asterisk_conf, 0o644),
        'pjsip.conf': (pjsip_conf, 0o600),
        'extensions.conf': (extensions_conf, 0o644),
        'rtp.conf': (rtp_conf, 0o644),
        'modules.conf': (modules_conf, 0o644),
    }


def config_filenames() -> tuple[str, ...]:
    return (
        'asterisk.conf',
        'pjsip.conf',
        'extensions.conf',
        'rtp.conf',
        'modules.conf',
    )
